"""tornar ano do resultado opcional

Revision ID: 19912d15b477
Revises: feefb251296d
Create Date: 2026-09-07 21:27:22.423897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19912d15b477'
down_revision = 'feefb251296d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resultados', 'ano',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resultados', 'ano',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
