"""remover data de nascimento

Revision ID: ec8c7e950c44
Revises: f692e87c35fe
Create Date: 2026-09-07 16:24:22.674094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8c7e950c44'
down_revision = 'f692e87c35fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pombos', 'data_nascimento')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pombos', sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
