"""criar tabelas iniciais

Revision ID: f692e87c35fe
Revises: 
Create Date: 2026-09-07 16:06:24.026860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f692e87c35fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proprietarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('colombodromo', sa.String(length=200), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pombos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anilha', sa.String(length=50), nullable=False),
    sa.Column('sexo', sa.Enum('M', 'F', 'DESCONHECIDO', name='sexo'), nullable=False),
    sa.Column('cor', sa.String(length=100), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'REPRODUTOR', 'VENDIDO', 'FALECIDO', name='status_pombo'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('origem', sa.String(length=200), nullable=True),
    sa.Column('proprietario_id', sa.Integer(), nullable=True),
    sa.Column('pai_id', sa.Integer(), nullable=True),
    sa.Column('mae_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mae_id'], ['pombos.id'], ),
    sa.ForeignKeyConstraint(['pai_id'], ['pombos.id'], ),
    sa.ForeignKeyConstraint(['proprietario_id'], ['proprietarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pombos_anilha'), 'pombos', ['anilha'], unique=True)
    op.create_table('resultados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pombo_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('competicao', sa.String(length=200), nullable=False),
    sa.Column('distancia_km', sa.Integer(), nullable=True),
    sa.Column('colocacao', sa.String(length=100), nullable=True),
    sa.Column('premio', sa.String(length=200), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pombo_id'], ['pombos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados')
    op.drop_index(op.f('ix_pombos_anilha'), table_name='pombos')
    op.drop_table('pombos')
    op.drop_table('proprietarios')
    # ### end Alembic commands ###
