"""adicionar observacoes ao proprietario

Revision ID: feefb251296d
Revises: ec8c7e950c44
Create Date: 2026-09-07 17:02:03.339876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feefb251296d'
down_revision = 'ec8c7e950c44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proprietarios', sa.Column('observacoes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proprietarios', 'observacoes')
    # ### end Alembic commands ###
